### PR TITLE
Made requireable server-side when window undefined.

### PR DESCRIPTION
**Pull request by callumacrae**
This makes when-scroll work with Vue server-side rendering.

@djgrant @mrcthms: Does this have any affect on React SSR that you're aware of? (planning on merging and releasing this afternoon)

### CODE REVIEW

**Comment by djgrant** [comment]
No issues that I'm aware of. We're only using it inside componentWillMount so affect us anyway.

**Comment by callumacrae** [comment]
Iirc it's being required inside componentWillMount as well, right? This change should mean it can happening using an `import` in the top of the script.

**Comment by djgrant** [comment]
That's correct. Great, will give it a go as an import when you release.

**Comment by callumacrae** [comment]
Published as when-scroll@0.3.1

**Pull request merged**
